/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardRoleAdminRouteImport } from './routes/dashboard/role/admin'
import { Route as DashboardProductsProductListRouteImport } from './routes/dashboard/products/productList'
import { Route as DashboardOrdersOrderListRouteImport } from './routes/dashboard/orders/orderList'
import { Route as DashboardCustomersCustomerListRouteImport } from './routes/dashboard/customers/customerList'
import { Route as DashboardProductsCategoriesRouteRouteImport } from './routes/dashboard/products/categories/route'
import { Route as DashboardProductsCategoriesIndexRouteImport } from './routes/dashboard/products/categories/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRoleAdminRoute = DashboardRoleAdminRouteImport.update({
  id: '/role/admin',
  path: '/role/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsProductListRoute =
  DashboardProductsProductListRouteImport.update({
    id: '/products/productList',
    path: '/products/productList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersOrderListRoute =
  DashboardOrdersOrderListRouteImport.update({
    id: '/orders/orderList',
    path: '/orders/orderList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCustomersCustomerListRoute =
  DashboardCustomersCustomerListRouteImport.update({
    id: '/customers/customerList',
    path: '/customers/customerList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsCategoriesRouteRoute =
  DashboardProductsCategoriesRouteRouteImport.update({
    id: '/products/categories',
    path: '/products/categories',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsCategoriesIndexRoute =
  DashboardProductsCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProductsCategoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/categories': typeof DashboardProductsCategoriesRouteRouteWithChildren
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/products/categories/': typeof DashboardProductsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/products/categories': typeof DashboardProductsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/products/categories': typeof DashboardProductsCategoriesRouteRouteWithChildren
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/products/categories/': typeof DashboardProductsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/products/categories'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/products/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/products/categories'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/products/categories'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/products/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/settings/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/role/admin': {
      id: '/dashboard/role/admin'
      path: '/role/admin'
      fullPath: '/dashboard/role/admin'
      preLoaderRoute: typeof DashboardRoleAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/productList': {
      id: '/dashboard/products/productList'
      path: '/products/productList'
      fullPath: '/dashboard/products/productList'
      preLoaderRoute: typeof DashboardProductsProductListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/orderList': {
      id: '/dashboard/orders/orderList'
      path: '/orders/orderList'
      fullPath: '/dashboard/orders/orderList'
      preLoaderRoute: typeof DashboardOrdersOrderListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers/customerList': {
      id: '/dashboard/customers/customerList'
      path: '/customers/customerList'
      fullPath: '/dashboard/customers/customerList'
      preLoaderRoute: typeof DashboardCustomersCustomerListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/categories': {
      id: '/dashboard/products/categories'
      path: '/products/categories'
      fullPath: '/dashboard/products/categories'
      preLoaderRoute: typeof DashboardProductsCategoriesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/categories/': {
      id: '/dashboard/products/categories/'
      path: '/'
      fullPath: '/dashboard/products/categories/'
      preLoaderRoute: typeof DashboardProductsCategoriesIndexRouteImport
      parentRoute: typeof DashboardProductsCategoriesRouteRoute
    }
  }
}

interface DashboardProductsCategoriesRouteRouteChildren {
  DashboardProductsCategoriesIndexRoute: typeof DashboardProductsCategoriesIndexRoute
}

const DashboardProductsCategoriesRouteRouteChildren: DashboardProductsCategoriesRouteRouteChildren =
  {
    DashboardProductsCategoriesIndexRoute:
      DashboardProductsCategoriesIndexRoute,
  }

const DashboardProductsCategoriesRouteRouteWithChildren =
  DashboardProductsCategoriesRouteRoute._addFileChildren(
    DashboardProductsCategoriesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsCategoriesRouteRoute: typeof DashboardProductsCategoriesRouteRouteWithChildren
  DashboardCustomersCustomerListRoute: typeof DashboardCustomersCustomerListRoute
  DashboardOrdersOrderListRoute: typeof DashboardOrdersOrderListRoute
  DashboardProductsProductListRoute: typeof DashboardProductsProductListRoute
  DashboardRoleAdminRoute: typeof DashboardRoleAdminRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsCategoriesRouteRoute:
    DashboardProductsCategoriesRouteRouteWithChildren,
  DashboardCustomersCustomerListRoute: DashboardCustomersCustomerListRoute,
  DashboardOrdersOrderListRoute: DashboardOrdersOrderListRoute,
  DashboardProductsProductListRoute: DashboardProductsProductListRoute,
  DashboardRoleAdminRoute: DashboardRoleAdminRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
