/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardRolesIndexRouteImport } from './routes/dashboard/roles/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard/settings/billing'
import { Route as DashboardRoleAdminRouteImport } from './routes/dashboard/role/admin'
import { Route as DashboardProductsProductListRouteImport } from './routes/dashboard/products/productList'
import { Route as DashboardOrdersOrderListRouteImport } from './routes/dashboard/orders/orderList'
import { Route as DashboardCustomersCustomerListRouteImport } from './routes/dashboard/customers/customerList'
import { Route as DashboardUsersCustomersIndexRouteImport } from './routes/dashboard/users/customers/index'
import { Route as DashboardUsersAdminsIndexRouteImport } from './routes/dashboard/users/admins/index'
import { Route as DashboardSettingsPaymentsIndexRouteImport } from './routes/dashboard/settings/payments/index'
import { Route as DashboardProductsRatesIndexRouteImport } from './routes/dashboard/products/rates/index'
import { Route as DashboardProductsMetalsIndexRouteImport } from './routes/dashboard/products/metals/index'
import { Route as DashboardProductsCreateIndexRouteImport } from './routes/dashboard/products/create/index'
import { Route as DashboardProductsCollectionsIndexRouteImport } from './routes/dashboard/products/collections/index'
import { Route as DashboardProductsCategoriesIndexRouteImport } from './routes/dashboard/products/categories/index'
import { Route as DashboardProductsBrandsIndexRouteImport } from './routes/dashboard/products/brands/index'
import { Route as DashboardProductsProductIdIndexRouteImport } from './routes/dashboard/products/$productId/index'
import { Route as DashboardOrdersPosIndexRouteImport } from './routes/dashboard/orders/pos/index'
import { Route as DashboardMarketingSlidesIndexRouteImport } from './routes/dashboard/marketing/slides/index'
import { Route as DashboardMarketingPromoCodesIndexRouteImport } from './routes/dashboard/marketing/promo-codes/index'
import { Route as DashboardDeliveryZonesIndexRouteImport } from './routes/dashboard/delivery/zones/index'
import { Route as DashboardCatalogAttributesIndexRouteImport } from './routes/dashboard/catalog/attributes/index'
import { Route as DashboardProductsProductIdEditIndexRouteImport } from './routes/dashboard/products/$productId/edit/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRoleAdminRoute = DashboardRoleAdminRouteImport.update({
  id: '/role/admin',
  path: '/role/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsProductListRoute =
  DashboardProductsProductListRouteImport.update({
    id: '/products/productList',
    path: '/products/productList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersOrderListRoute =
  DashboardOrdersOrderListRouteImport.update({
    id: '/orders/orderList',
    path: '/orders/orderList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCustomersCustomerListRoute =
  DashboardCustomersCustomerListRouteImport.update({
    id: '/customers/customerList',
    path: '/customers/customerList',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersCustomersIndexRoute =
  DashboardUsersCustomersIndexRouteImport.update({
    id: '/users/customers/',
    path: '/users/customers/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersAdminsIndexRoute =
  DashboardUsersAdminsIndexRouteImport.update({
    id: '/users/admins/',
    path: '/users/admins/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsPaymentsIndexRoute =
  DashboardSettingsPaymentsIndexRouteImport.update({
    id: '/settings/payments/',
    path: '/settings/payments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsRatesIndexRoute =
  DashboardProductsRatesIndexRouteImport.update({
    id: '/products/rates/',
    path: '/products/rates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsMetalsIndexRoute =
  DashboardProductsMetalsIndexRouteImport.update({
    id: '/products/metals/',
    path: '/products/metals/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsCreateIndexRoute =
  DashboardProductsCreateIndexRouteImport.update({
    id: '/products/create/',
    path: '/products/create/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsCollectionsIndexRoute =
  DashboardProductsCollectionsIndexRouteImport.update({
    id: '/products/collections/',
    path: '/products/collections/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsCategoriesIndexRoute =
  DashboardProductsCategoriesIndexRouteImport.update({
    id: '/products/categories/',
    path: '/products/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsBrandsIndexRoute =
  DashboardProductsBrandsIndexRouteImport.update({
    id: '/products/brands/',
    path: '/products/brands/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsProductIdIndexRoute =
  DashboardProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrdersPosIndexRoute = DashboardOrdersPosIndexRouteImport.update({
  id: '/orders/pos/',
  path: '/orders/pos/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketingSlidesIndexRoute =
  DashboardMarketingSlidesIndexRouteImport.update({
    id: '/marketing/slides/',
    path: '/marketing/slides/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMarketingPromoCodesIndexRoute =
  DashboardMarketingPromoCodesIndexRouteImport.update({
    id: '/marketing/promo-codes/',
    path: '/marketing/promo-codes/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDeliveryZonesIndexRoute =
  DashboardDeliveryZonesIndexRouteImport.update({
    id: '/delivery/zones/',
    path: '/delivery/zones/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogAttributesIndexRoute =
  DashboardCatalogAttributesIndexRouteImport.update({
    id: '/catalog/attributes/',
    path: '/catalog/attributes/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsProductIdEditIndexRoute =
  DashboardProductsProductIdEditIndexRouteImport.update({
    id: '/products/$productId/edit/',
    path: '/products/$productId/edit/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/catalog/attributes': typeof DashboardCatalogAttributesIndexRoute
  '/dashboard/delivery/zones': typeof DashboardDeliveryZonesIndexRoute
  '/dashboard/marketing/promo-codes': typeof DashboardMarketingPromoCodesIndexRoute
  '/dashboard/marketing/slides': typeof DashboardMarketingSlidesIndexRoute
  '/dashboard/orders/pos': typeof DashboardOrdersPosIndexRoute
  '/dashboard/products/$productId': typeof DashboardProductsProductIdIndexRoute
  '/dashboard/products/brands': typeof DashboardProductsBrandsIndexRoute
  '/dashboard/products/categories': typeof DashboardProductsCategoriesIndexRoute
  '/dashboard/products/collections': typeof DashboardProductsCollectionsIndexRoute
  '/dashboard/products/create': typeof DashboardProductsCreateIndexRoute
  '/dashboard/products/metals': typeof DashboardProductsMetalsIndexRoute
  '/dashboard/products/rates': typeof DashboardProductsRatesIndexRoute
  '/dashboard/settings/payments': typeof DashboardSettingsPaymentsIndexRoute
  '/dashboard/users/admins': typeof DashboardUsersAdminsIndexRoute
  '/dashboard/users/customers': typeof DashboardUsersCustomersIndexRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/catalog/attributes': typeof DashboardCatalogAttributesIndexRoute
  '/dashboard/delivery/zones': typeof DashboardDeliveryZonesIndexRoute
  '/dashboard/marketing/promo-codes': typeof DashboardMarketingPromoCodesIndexRoute
  '/dashboard/marketing/slides': typeof DashboardMarketingSlidesIndexRoute
  '/dashboard/orders/pos': typeof DashboardOrdersPosIndexRoute
  '/dashboard/products/$productId': typeof DashboardProductsProductIdIndexRoute
  '/dashboard/products/brands': typeof DashboardProductsBrandsIndexRoute
  '/dashboard/products/categories': typeof DashboardProductsCategoriesIndexRoute
  '/dashboard/products/collections': typeof DashboardProductsCollectionsIndexRoute
  '/dashboard/products/create': typeof DashboardProductsCreateIndexRoute
  '/dashboard/products/metals': typeof DashboardProductsMetalsIndexRoute
  '/dashboard/products/rates': typeof DashboardProductsRatesIndexRoute
  '/dashboard/settings/payments': typeof DashboardSettingsPaymentsIndexRoute
  '/dashboard/users/admins': typeof DashboardUsersAdminsIndexRoute
  '/dashboard/users/customers': typeof DashboardUsersCustomersIndexRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/customers/customerList': typeof DashboardCustomersCustomerListRoute
  '/dashboard/orders/orderList': typeof DashboardOrdersOrderListRoute
  '/dashboard/products/productList': typeof DashboardProductsProductListRoute
  '/dashboard/role/admin': typeof DashboardRoleAdminRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/catalog/attributes/': typeof DashboardCatalogAttributesIndexRoute
  '/dashboard/delivery/zones/': typeof DashboardDeliveryZonesIndexRoute
  '/dashboard/marketing/promo-codes/': typeof DashboardMarketingPromoCodesIndexRoute
  '/dashboard/marketing/slides/': typeof DashboardMarketingSlidesIndexRoute
  '/dashboard/orders/pos/': typeof DashboardOrdersPosIndexRoute
  '/dashboard/products/$productId/': typeof DashboardProductsProductIdIndexRoute
  '/dashboard/products/brands/': typeof DashboardProductsBrandsIndexRoute
  '/dashboard/products/categories/': typeof DashboardProductsCategoriesIndexRoute
  '/dashboard/products/collections/': typeof DashboardProductsCollectionsIndexRoute
  '/dashboard/products/create/': typeof DashboardProductsCreateIndexRoute
  '/dashboard/products/metals/': typeof DashboardProductsMetalsIndexRoute
  '/dashboard/products/rates/': typeof DashboardProductsRatesIndexRoute
  '/dashboard/settings/payments/': typeof DashboardSettingsPaymentsIndexRoute
  '/dashboard/users/admins/': typeof DashboardUsersAdminsIndexRoute
  '/dashboard/users/customers/': typeof DashboardUsersCustomersIndexRoute
  '/dashboard/products/$productId/edit/': typeof DashboardProductsProductIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/roles'
    | '/dashboard/catalog/attributes'
    | '/dashboard/delivery/zones'
    | '/dashboard/marketing/promo-codes'
    | '/dashboard/marketing/slides'
    | '/dashboard/orders/pos'
    | '/dashboard/products/$productId'
    | '/dashboard/products/brands'
    | '/dashboard/products/categories'
    | '/dashboard/products/collections'
    | '/dashboard/products/create'
    | '/dashboard/products/metals'
    | '/dashboard/products/rates'
    | '/dashboard/settings/payments'
    | '/dashboard/users/admins'
    | '/dashboard/users/customers'
    | '/dashboard/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/roles'
    | '/dashboard/catalog/attributes'
    | '/dashboard/delivery/zones'
    | '/dashboard/marketing/promo-codes'
    | '/dashboard/marketing/slides'
    | '/dashboard/orders/pos'
    | '/dashboard/products/$productId'
    | '/dashboard/products/brands'
    | '/dashboard/products/categories'
    | '/dashboard/products/collections'
    | '/dashboard/products/create'
    | '/dashboard/products/metals'
    | '/dashboard/products/rates'
    | '/dashboard/settings/payments'
    | '/dashboard/users/admins'
    | '/dashboard/users/customers'
    | '/dashboard/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/customers/customerList'
    | '/dashboard/orders/orderList'
    | '/dashboard/products/productList'
    | '/dashboard/role/admin'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/roles/'
    | '/dashboard/catalog/attributes/'
    | '/dashboard/delivery/zones/'
    | '/dashboard/marketing/promo-codes/'
    | '/dashboard/marketing/slides/'
    | '/dashboard/orders/pos/'
    | '/dashboard/products/$productId/'
    | '/dashboard/products/brands/'
    | '/dashboard/products/categories/'
    | '/dashboard/products/collections/'
    | '/dashboard/products/create/'
    | '/dashboard/products/metals/'
    | '/dashboard/products/rates/'
    | '/dashboard/settings/payments/'
    | '/dashboard/users/admins/'
    | '/dashboard/users/customers/'
    | '/dashboard/products/$productId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles/': {
      id: '/dashboard/roles/'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/settings/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/role/admin': {
      id: '/dashboard/role/admin'
      path: '/role/admin'
      fullPath: '/dashboard/role/admin'
      preLoaderRoute: typeof DashboardRoleAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/productList': {
      id: '/dashboard/products/productList'
      path: '/products/productList'
      fullPath: '/dashboard/products/productList'
      preLoaderRoute: typeof DashboardProductsProductListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/orderList': {
      id: '/dashboard/orders/orderList'
      path: '/orders/orderList'
      fullPath: '/dashboard/orders/orderList'
      preLoaderRoute: typeof DashboardOrdersOrderListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers/customerList': {
      id: '/dashboard/customers/customerList'
      path: '/customers/customerList'
      fullPath: '/dashboard/customers/customerList'
      preLoaderRoute: typeof DashboardCustomersCustomerListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/customers/': {
      id: '/dashboard/users/customers/'
      path: '/users/customers'
      fullPath: '/dashboard/users/customers'
      preLoaderRoute: typeof DashboardUsersCustomersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/admins/': {
      id: '/dashboard/users/admins/'
      path: '/users/admins'
      fullPath: '/dashboard/users/admins'
      preLoaderRoute: typeof DashboardUsersAdminsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/payments/': {
      id: '/dashboard/settings/payments/'
      path: '/settings/payments'
      fullPath: '/dashboard/settings/payments'
      preLoaderRoute: typeof DashboardSettingsPaymentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/rates/': {
      id: '/dashboard/products/rates/'
      path: '/products/rates'
      fullPath: '/dashboard/products/rates'
      preLoaderRoute: typeof DashboardProductsRatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/metals/': {
      id: '/dashboard/products/metals/'
      path: '/products/metals'
      fullPath: '/dashboard/products/metals'
      preLoaderRoute: typeof DashboardProductsMetalsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/create/': {
      id: '/dashboard/products/create/'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/collections/': {
      id: '/dashboard/products/collections/'
      path: '/products/collections'
      fullPath: '/dashboard/products/collections'
      preLoaderRoute: typeof DashboardProductsCollectionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/categories/': {
      id: '/dashboard/products/categories/'
      path: '/products/categories'
      fullPath: '/dashboard/products/categories'
      preLoaderRoute: typeof DashboardProductsCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/brands/': {
      id: '/dashboard/products/brands/'
      path: '/products/brands'
      fullPath: '/dashboard/products/brands'
      preLoaderRoute: typeof DashboardProductsBrandsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/$productId/': {
      id: '/dashboard/products/$productId/'
      path: '/products/$productId'
      fullPath: '/dashboard/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/pos/': {
      id: '/dashboard/orders/pos/'
      path: '/orders/pos'
      fullPath: '/dashboard/orders/pos'
      preLoaderRoute: typeof DashboardOrdersPosIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing/slides/': {
      id: '/dashboard/marketing/slides/'
      path: '/marketing/slides'
      fullPath: '/dashboard/marketing/slides'
      preLoaderRoute: typeof DashboardMarketingSlidesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing/promo-codes/': {
      id: '/dashboard/marketing/promo-codes/'
      path: '/marketing/promo-codes'
      fullPath: '/dashboard/marketing/promo-codes'
      preLoaderRoute: typeof DashboardMarketingPromoCodesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/delivery/zones/': {
      id: '/dashboard/delivery/zones/'
      path: '/delivery/zones'
      fullPath: '/dashboard/delivery/zones'
      preLoaderRoute: typeof DashboardDeliveryZonesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/attributes/': {
      id: '/dashboard/catalog/attributes/'
      path: '/catalog/attributes'
      fullPath: '/dashboard/catalog/attributes'
      preLoaderRoute: typeof DashboardCatalogAttributesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/$productId/edit/': {
      id: '/dashboard/products/$productId/edit/'
      path: '/products/$productId/edit'
      fullPath: '/dashboard/products/$productId/edit'
      preLoaderRoute: typeof DashboardProductsProductIdEditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCustomersCustomerListRoute: typeof DashboardCustomersCustomerListRoute
  DashboardOrdersOrderListRoute: typeof DashboardOrdersOrderListRoute
  DashboardProductsProductListRoute: typeof DashboardProductsProductListRoute
  DashboardRoleAdminRoute: typeof DashboardRoleAdminRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
  DashboardCatalogAttributesIndexRoute: typeof DashboardCatalogAttributesIndexRoute
  DashboardDeliveryZonesIndexRoute: typeof DashboardDeliveryZonesIndexRoute
  DashboardMarketingPromoCodesIndexRoute: typeof DashboardMarketingPromoCodesIndexRoute
  DashboardMarketingSlidesIndexRoute: typeof DashboardMarketingSlidesIndexRoute
  DashboardOrdersPosIndexRoute: typeof DashboardOrdersPosIndexRoute
  DashboardProductsProductIdIndexRoute: typeof DashboardProductsProductIdIndexRoute
  DashboardProductsBrandsIndexRoute: typeof DashboardProductsBrandsIndexRoute
  DashboardProductsCategoriesIndexRoute: typeof DashboardProductsCategoriesIndexRoute
  DashboardProductsCollectionsIndexRoute: typeof DashboardProductsCollectionsIndexRoute
  DashboardProductsCreateIndexRoute: typeof DashboardProductsCreateIndexRoute
  DashboardProductsMetalsIndexRoute: typeof DashboardProductsMetalsIndexRoute
  DashboardProductsRatesIndexRoute: typeof DashboardProductsRatesIndexRoute
  DashboardSettingsPaymentsIndexRoute: typeof DashboardSettingsPaymentsIndexRoute
  DashboardUsersAdminsIndexRoute: typeof DashboardUsersAdminsIndexRoute
  DashboardUsersCustomersIndexRoute: typeof DashboardUsersCustomersIndexRoute
  DashboardProductsProductIdEditIndexRoute: typeof DashboardProductsProductIdEditIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCustomersCustomerListRoute: DashboardCustomersCustomerListRoute,
  DashboardOrdersOrderListRoute: DashboardOrdersOrderListRoute,
  DashboardProductsProductListRoute: DashboardProductsProductListRoute,
  DashboardRoleAdminRoute: DashboardRoleAdminRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
  DashboardCatalogAttributesIndexRoute: DashboardCatalogAttributesIndexRoute,
  DashboardDeliveryZonesIndexRoute: DashboardDeliveryZonesIndexRoute,
  DashboardMarketingPromoCodesIndexRoute:
    DashboardMarketingPromoCodesIndexRoute,
  DashboardMarketingSlidesIndexRoute: DashboardMarketingSlidesIndexRoute,
  DashboardOrdersPosIndexRoute: DashboardOrdersPosIndexRoute,
  DashboardProductsProductIdIndexRoute: DashboardProductsProductIdIndexRoute,
  DashboardProductsBrandsIndexRoute: DashboardProductsBrandsIndexRoute,
  DashboardProductsCategoriesIndexRoute: DashboardProductsCategoriesIndexRoute,
  DashboardProductsCollectionsIndexRoute:
    DashboardProductsCollectionsIndexRoute,
  DashboardProductsCreateIndexRoute: DashboardProductsCreateIndexRoute,
  DashboardProductsMetalsIndexRoute: DashboardProductsMetalsIndexRoute,
  DashboardProductsRatesIndexRoute: DashboardProductsRatesIndexRoute,
  DashboardSettingsPaymentsIndexRoute: DashboardSettingsPaymentsIndexRoute,
  DashboardUsersAdminsIndexRoute: DashboardUsersAdminsIndexRoute,
  DashboardUsersCustomersIndexRoute: DashboardUsersCustomersIndexRoute,
  DashboardProductsProductIdEditIndexRoute:
    DashboardProductsProductIdEditIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
