"""Add delivery zones

Revision ID: 0d95432d16c7
Revises: c558f474d7ad
Create Date: 2026-01-04 14:40:30.643730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d95432d16c7'
down_revision: Union[str, None] = 'c558f474d7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('districts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('charge_type', sa.Enum('FIXED', 'WEIGHT_BASED', name='chargetype'), nullable=False),
    sa.Column('base_charge', sa.Numeric(), nullable=False),
    sa.Column('per_kg_charge', sa.Numeric(), nullable=True),
    sa.Column('free_above', sa.Numeric(), nullable=True),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
