"""add_scopes_to_oauth_provider

Revision ID: 0e8bd7470ef2
Revises: 4a78a828ffc8
Create Date: 2025-12-10 06:39:26.588726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e8bd7470ef2'
down_revision: Union[str, None] = '4a78a828ffc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_providers', sa.Column('scopes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_providers', 'scopes')
    # ### end Alembic commands ###
