"""Add orders

Revision ID: 3559f85fe667
Revises: 7229d97c6d35
Create Date: 2026-01-04 15:00:09.762764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3559f85fe667'
down_revision: Union[str, None] = '7229d97c6d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('is_pos_order', sa.Boolean(), nullable=False),
    sa.Column('pos_customer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('pos_customer_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), nullable=False),
    sa.Column('gift_message', sa.Text(), nullable=True),
    sa.Column('hide_prices', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(), nullable=False),
    sa.Column('delivery_charge', sa.Numeric(), nullable=False),
    sa.Column('tax_amount', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('promo_code_id', sa.Uuid(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_transaction_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('variant_sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('product_image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metal_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('metal_purity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('metal_color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.Column('net_weight', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
