"""Make permission resource and action optional

Revision ID: 4a78a828ffc8
Revises: 976090f5b591
Create Date: 2025-12-10 05:57:04.587049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a78a828ffc8'
down_revision: Union[str, None] = '976090f5b591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.alter_column('permissions', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('permissions', 'resource',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('permissions', 'resource',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###
