"""add position field to slides

Revision ID: 521bccba55e7
Revises: bc1836e6e0cd
Create Date: 2026-03-08 04:31:43.946561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '521bccba55e7'
down_revision: Union[str, None] = 'bc1836e6e0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_slides_position'), 'slides', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_position'), table_name='slides')
    op.drop_column('slides', 'position')
    # ### end Alembic commands ###
