"""user.role to user.user_type

Revision ID: 60007f977264
Revises: 2b10fe0140db
Create Date: 2025-12-11 20:11:19.338918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60007f977264'
down_revision: Union[str, None] = '2b10fe0140db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly create the new Enum type
    usertype = sa.Enum('ADMIN', 'CUSTOMER', name='usertype')
    usertype.create(op.get_bind())
    
    # 1. Add column as nullable
    op.add_column('users', sa.Column('user_type', usertype, nullable=True))
    
    # 2. Backfill data from role column
    # casting 'role' (userrole enum) to text, then to 'user_type' (usertype enum)
    op.execute("UPDATE users SET user_type = role::text::usertype")
    
    # 3. Make column not nullable
    op.alter_column('users', 'user_type', nullable=False)
    
    # 4. Drop old column
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'CUSTOMER', name='userrole'), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_type')
    
    # Explicitly drop the new Enum type
    sa.Enum(name='usertype').drop(op.get_bind())
    # ### end Alembic commands ###
