"""add slides table

Revision ID: 764809c64255
Revises: aa188bf02efe
Create Date: 2026-01-03 11:23:41.202871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '764809c64255'
down_revision: Union[str, None] = 'aa188bf02efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_alt', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link_text', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('slide_type', sa.Enum('BANNER', 'PROMO', 'OFFER', 'COLLECTION', name='slidetype'), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('overlay_color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slides_title'), 'slides', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_title'), table_name='slides')
    op.drop_table('slides')
    # ### end Alembic commands ###
