"""add_gift_cards_tables

Revision ID: 872b40c186cc
Revises: 521bccba55e7
Create Date: 2026-03-08 23:16:05.421432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '872b40c186cc'
down_revision: Union[str, None] = '521bccba55e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('purchased_by', sa.Uuid(), nullable=True),
    sa.Column('purchased_order_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('personal_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXHAUSTED', 'EXPIRED', 'CANCELLED', name='giftcardstatus'), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchased_by'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['purchased_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_cards_code'), 'gift_cards', ['code'], unique=True)
    op.create_index(op.f('ix_gift_cards_purchased_by'), 'gift_cards', ['purchased_by'], unique=False)
    op.create_table('gift_card_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gift_card_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('redeemed_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('channel', sa.Enum('ONLINE', 'POS', name='giftcardchannel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_card_transactions_gift_card_id'), 'gift_card_transactions', ['gift_card_id'], unique=False)
    op.add_column('orders', sa.Column('gift_card_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('orders', sa.Column('gift_card_discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'gift_card_discount')
    op.drop_column('orders', 'gift_card_code')
    op.drop_index(op.f('ix_gift_card_transactions_gift_card_id'), table_name='gift_card_transactions')
    op.drop_table('gift_card_transactions')
    op.drop_index(op.f('ix_gift_cards_purchased_by'), table_name='gift_cards')
    op.drop_index(op.f('ix_gift_cards_code'), table_name='gift_cards')
    op.drop_table('gift_cards')
    op.execute("DROP TYPE IF EXISTS giftcardstatus")
    op.execute("DROP TYPE IF EXISTS giftcardchannel")
    # ### end Alembic commands ###
