"""add_attribute_system_tables

Revision ID: a9b950755c26
Revises: 16984cb555ff
Create Date: 2026-01-02 17:33:08.005547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9b950755c26'
down_revision: Union[str, None] = '16984cb555ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_groups',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_groups_name'), 'attribute_groups', ['name'], unique=False)
    op.create_table('attributes',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'BOOLEAN', name='attributetype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['attribute_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_code'), 'attributes', ['code'], unique=True)
    op.create_index(op.f('ix_attributes_group_id'), 'attributes', ['group_id'], unique=False)
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_product_id'), 'product_attribute_values', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_attribute_values_product_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_group_id'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_code'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_attribute_groups_name'), table_name='attribute_groups')
    op.drop_table('attribute_groups')
    # ### end Alembic commands ###
