"""add_daily_rates_table

Revision ID: aa188bf02efe
Revises: a9b950755c26
Create Date: 2026-01-02 17:36:08.762762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa188bf02efe'
down_revision: Union[str, None] = 'a9b950755c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_rates',
    sa.Column('source', sa.Enum('BAJUS', 'MANUAL', 'API', name='ratesource'), nullable=False),
    sa.Column('metal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate_per_gram', sa.Numeric(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_rates_effective_date'), 'daily_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_daily_rates_metal_id'), 'daily_rates', ['metal_id'], unique=False)
    op.create_index(op.f('ix_daily_rates_metal_type'), 'daily_rates', ['metal_type'], unique=False)
    op.create_index(op.f('ix_daily_rates_purity'), 'daily_rates', ['purity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_rates_purity'), table_name='daily_rates')
    op.drop_index(op.f('ix_daily_rates_metal_type'), table_name='daily_rates')
    op.drop_index(op.f('ix_daily_rates_metal_id'), table_name='daily_rates')
    op.drop_index(op.f('ix_daily_rates_effective_date'), table_name='daily_rates')
    op.drop_table('daily_rates')
    # ### end Alembic commands ###
