"""empty message

Revision ID: c8092637c863
Revises: 521bccba55e7
Create Date: 2026-03-17 11:02:50.679514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8092637c863'
down_revision: Union[str, None] = '521bccba55e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('products', sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('products', sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'meta_title')
    # ### end Alembic commands ###
