"""add_metals_and_purities_tables

Revision ID: e26a44979c0a
Revises: 18e7618fe312
Create Date: 2026-01-02 17:26:33.143633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e26a44979c0a'
down_revision: Union[str, None] = '18e7618fe312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metals',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metals_code'), 'metals', ['code'], unique=True)
    op.create_index(op.f('ix_metals_name'), 'metals', ['name'], unique=False)
    op.create_table('purities',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fineness', sa.Numeric(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purities_code'), 'purities', ['code'], unique=True)
    op.create_index(op.f('ix_purities_metal_id'), 'purities', ['metal_id'], unique=False)
    op.create_index(op.f('ix_purities_name'), 'purities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purities_name'), table_name='purities')
    op.drop_index(op.f('ix_purities_metal_id'), table_name='purities')
    op.drop_index(op.f('ix_purities_code'), table_name='purities')
    op.drop_table('purities')
    op.drop_index(op.f('ix_metals_name'), table_name='metals')
    op.drop_index(op.f('ix_metals_code'), table_name='metals')
    op.drop_table('metals')
    # ### end Alembic commands ###
