"""Add promo codes

Revision ID: e38330055f45
Revises: 0d95432d16c7
Create Date: 2026-01-04 14:48:48.708606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e38330055f45'
down_revision: Union[str, None] = '0d95432d16c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(), nullable=False),
    sa.Column('max_discount', sa.Numeric(), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(), nullable=True),
    sa.Column('max_total_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('first_order_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('promo_code_uses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('promo_code_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_uses_customer_id'), 'promo_code_uses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_promo_code_uses_order_id'), 'promo_code_uses', ['order_id'], unique=False)
    op.create_index(op.f('ix_promo_code_uses_promo_code_id'), 'promo_code_uses', ['promo_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code_uses_promo_code_id'), table_name='promo_code_uses')
    op.drop_index(op.f('ix_promo_code_uses_order_id'), table_name='promo_code_uses')
    op.drop_index(op.f('ix_promo_code_uses_customer_id'), table_name='promo_code_uses')
    op.drop_table('promo_code_uses')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
