/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _errorRouteImport } from './routes/__error'
import { Route as SplatRouteImport } from './routes/$'
import { Route as WishlistRouteRouteImport } from './routes/wishlist/route'
import { Route as StoresRouteRouteImport } from './routes/stores/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as OrdersRouteRouteImport } from './routes/orders/route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as CartRouteRouteImport } from './routes/cart/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as ProfileAddressesRouteImport } from './routes/profile/addresses'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as FooterTrackOrderRouteImport } from './routes/footer/track-order'
import { Route as FooterSizeGuideRouteImport } from './routes/footer/size-guide'
import { Route as FooterOurPoliciesRouteImport } from './routes/footer/our-policies'
import { Route as FooterMetalPricesRouteImport } from './routes/footer/metal-prices'
import { Route as FooterFaqRouteImport } from './routes/footer/faq'
import { Route as FooterCustomJewelleryRouteImport } from './routes/footer/custom-jewellery'
import { Route as FooterAboutRouteImport } from './routes/footer/about'
import { Route as GiftCardsIndexRouteImport } from './routes/gift-cards/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'

const _errorRoute = _errorRouteImport.update({
  id: '/__error',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRouteRoute = WishlistRouteRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRouteRoute = StoresRouteRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRouteRoute = OrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const FooterTrackOrderRoute = FooterTrackOrderRouteImport.update({
  id: '/footer/track-order',
  path: '/footer/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterSizeGuideRoute = FooterSizeGuideRouteImport.update({
  id: '/footer/size-guide',
  path: '/footer/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterOurPoliciesRoute = FooterOurPoliciesRouteImport.update({
  id: '/footer/our-policies',
  path: '/footer/our-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterMetalPricesRoute = FooterMetalPricesRouteImport.update({
  id: '/footer/metal-prices',
  path: '/footer/metal-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterFaqRoute = FooterFaqRouteImport.update({
  id: '/footer/faq',
  path: '/footer/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterCustomJewelleryRoute = FooterCustomJewelleryRouteImport.update({
  id: '/footer/custom-jewellery',
  path: '/footer/custom-jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterAboutRoute = FooterAboutRouteImport.update({
  id: '/footer/about',
  path: '/footer/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsIndexRoute = GiftCardsIndexRouteImport.update({
  id: '/gift-cards/',
  path: '/gift-cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/stores': typeof StoresRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/footer/about': typeof FooterAboutRoute
  '/footer/custom-jewellery': typeof FooterCustomJewelleryRoute
  '/footer/faq': typeof FooterFaqRoute
  '/footer/metal-prices': typeof FooterMetalPricesRoute
  '/footer/our-policies': typeof FooterOurPoliciesRoute
  '/footer/size-guide': typeof FooterSizeGuideRoute
  '/footer/track-order': typeof FooterTrackOrderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/orders/': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/stores': typeof StoresRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/gift-cards': typeof GiftCardsIndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/footer/about': typeof FooterAboutRoute
  '/footer/custom-jewellery': typeof FooterCustomJewelleryRoute
  '/footer/faq': typeof FooterFaqRoute
  '/footer/metal-prices': typeof FooterMetalPricesRoute
  '/footer/our-policies': typeof FooterOurPoliciesRoute
  '/footer/size-guide': typeof FooterSizeGuideRoute
  '/footer/track-order': typeof FooterTrackOrderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/stores': typeof StoresRouteRoute
  '/wishlist': typeof WishlistRouteRoute
  '/$': typeof SplatRoute
  '/__error': typeof _errorRoute
  '/gift-cards/': typeof GiftCardsIndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/footer/about': typeof FooterAboutRoute
  '/footer/custom-jewellery': typeof FooterCustomJewelleryRoute
  '/footer/faq': typeof FooterFaqRoute
  '/footer/metal-prices': typeof FooterMetalPricesRoute
  '/footer/our-policies': typeof FooterOurPoliciesRoute
  '/footer/size-guide': typeof FooterSizeGuideRoute
  '/footer/track-order': typeof FooterTrackOrderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/stores'
    | '/wishlist'
    | '/$'
    | '/gift-cards/'
    | '/categories/$slug'
    | '/footer/about'
    | '/footer/custom-jewellery'
    | '/footer/faq'
    | '/footer/metal-prices'
    | '/footer/our-policies'
    | '/footer/size-guide'
    | '/footer/track-order'
    | '/orders/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/orders/'
    | '/products'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/stores'
    | '/wishlist'
    | '/$'
    | '/gift-cards'
    | '/categories/$slug'
    | '/footer/about'
    | '/footer/custom-jewellery'
    | '/footer/faq'
    | '/footer/metal-prices'
    | '/footer/our-policies'
    | '/footer/size-guide'
    | '/footer/track-order'
    | '/orders/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/orders'
    | '/products'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/stores'
    | '/wishlist'
    | '/$'
    | '/__error'
    | '/gift-cards/'
    | '/categories/$slug'
    | '/footer/about'
    | '/footer/custom-jewellery'
    | '/footer/faq'
    | '/footer/metal-prices'
    | '/footer/our-policies'
    | '/footer/size-guide'
    | '/footer/track-order'
    | '/orders/$id'
    | '/products/$slug'
    | '/profile/addresses'
    | '/orders/'
    | '/products/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRouteRoute: typeof CartRouteRoute
  CheckoutRouteRoute: typeof CheckoutRouteRoute
  OrdersRouteRoute: typeof OrdersRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  StoresRouteRoute: typeof StoresRouteRoute
  WishlistRouteRoute: typeof WishlistRouteRoute
  SplatRoute: typeof SplatRoute
  _errorRoute: typeof _errorRoute
  GiftCardsIndexRoute: typeof GiftCardsIndexRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  FooterAboutRoute: typeof FooterAboutRoute
  FooterCustomJewelleryRoute: typeof FooterCustomJewelleryRoute
  FooterFaqRoute: typeof FooterFaqRoute
  FooterMetalPricesRoute: typeof FooterMetalPricesRoute
  FooterOurPoliciesRoute: typeof FooterOurPoliciesRoute
  FooterSizeGuideRoute: typeof FooterSizeGuideRoute
  FooterTrackOrderRoute: typeof FooterTrackOrderRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__error': {
      id: '/__error'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _errorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/footer/track-order': {
      id: '/footer/track-order'
      path: '/footer/track-order'
      fullPath: '/footer/track-order'
      preLoaderRoute: typeof FooterTrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/size-guide': {
      id: '/footer/size-guide'
      path: '/footer/size-guide'
      fullPath: '/footer/size-guide'
      preLoaderRoute: typeof FooterSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/our-policies': {
      id: '/footer/our-policies'
      path: '/footer/our-policies'
      fullPath: '/footer/our-policies'
      preLoaderRoute: typeof FooterOurPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/metal-prices': {
      id: '/footer/metal-prices'
      path: '/footer/metal-prices'
      fullPath: '/footer/metal-prices'
      preLoaderRoute: typeof FooterMetalPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/faq': {
      id: '/footer/faq'
      path: '/footer/faq'
      fullPath: '/footer/faq'
      preLoaderRoute: typeof FooterFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/custom-jewellery': {
      id: '/footer/custom-jewellery'
      path: '/footer/custom-jewellery'
      fullPath: '/footer/custom-jewellery'
      preLoaderRoute: typeof FooterCustomJewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/about': {
      id: '/footer/about'
      path: '/footer/about'
      fullPath: '/footer/about'
      preLoaderRoute: typeof FooterAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards/': {
      id: '/gift-cards/'
      path: '/gift-cards/'
      fullPath: '/gift-cards/'
      preLoaderRoute: typeof GiftCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteRouteChildren: OrdersRouteRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteRouteWithChildren = OrdersRouteRoute._addFileChildren(
  OrdersRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRouteRoute: CartRouteRoute,
  CheckoutRouteRoute: CheckoutRouteRoute,
  OrdersRouteRoute: OrdersRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  StoresRouteRoute: StoresRouteRoute,
  WishlistRouteRoute: WishlistRouteRoute,
  SplatRoute: SplatRoute,
  _errorRoute: _errorRoute,
  GiftCardsIndexRoute: GiftCardsIndexRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  FooterAboutRoute: FooterAboutRoute,
  FooterCustomJewelleryRoute: FooterCustomJewelleryRoute,
  FooterFaqRoute: FooterFaqRoute,
  FooterMetalPricesRoute: FooterMetalPricesRoute,
  FooterOurPoliciesRoute: FooterOurPoliciesRoute,
  FooterSizeGuideRoute: FooterSizeGuideRoute,
  FooterTrackOrderRoute: FooterTrackOrderRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
